# This file is covered by the LICENSE file in the root of this project.

#Training & Experiment params
n_epochs: 100
lr: 0.0002
batch_size: 1
lambda_A : 10
lambda_B: 10
lambda_identity: 0.5
name: test_cycle
gpu_ids: [0]
checkpoints_dir: './checkpoints'
fast_test: True
epoch: 'latest'
continue_train: False
load_iter: 0
display_freq: 2
print_freq: 2
save_latest_freq: 1
save_epoch_freq: 1
verbose: False
suffix : ''
val_split_ratio: 0.2
seed: 10


# model params
model: 'cycle_gan'
input_nc: 3
output_nc: 3
ngf : 64
ndf: 64
netD: 'basic'
netG: 'resnet_9blocks'
n_layers_D: 3
norm: 'batch'
init_type: 'normal'
init_gain: 0.02
no_dropout: True
gan_mode: 'lsgan'
pool_size: 50
lr_policy: 'linear'
lr_decay_iters: 50
beta1: 0.5

dataset:
  dataset_A:
    data_dir: '/media/oem/Local Disk/Phd-datasets/projected_kitti'
    sensor:
      name: "HDL64"
      type: "spherical" # projective
      fov_up: 3
      fov_down: -25 
      foh_left: 45
      foh_right: -45
      img_prop:
        width: 256
        height: 64
      img_means: #x,y,z, range, signal
        - 11.06
        - 0.25
        - -1.20
        - 12.29
        - 0.27
      img_stds: #x,y,z,range, signal
        - 10.10
        - 6.02
        - 0.78
        - 10.57
        - 0.13
      img_min:
        - 1.26
        - -56.34
        - -31.95
        - 1.78
        - 0.0
      img_max:
        - 79.99
        - 56.48
        - 2.95
        - 80.22
        - 0.99


  dataset_B:
    data_dir: '/media/oem/Local Disk/Phd-datasets/GTA_Lidar_selected_projected'
    sensor:
      name: "HDL64"
      type: "spherical" # projective
      fov_up: 3
      fov_down: -25 
      foh_left: 45
      foh_right: -45
      img_prop:
        width: 256
        height: 64
      img_means: #x,y,z, range, signal
        - 12.91
        - 0.34
        - -1.42
        - 14.46
        - 0.0
      img_stds: #x,y,z,range, signal
        - 15.93
        - 9.19
        - 0.74
        - 17.27
        - 0.0
      img_min:
        - 0.84
        - -84.81
        - -25.18
        - 1.19
        - 0.0
      img_max:
        - 119.98
        - 84.63
        - 3.30
        - 119.99
        - 1.0


