# This file is covered by the LICENSE file in the root of this project.

#Training & Experiment params
n_epochs: 100
lr: 0.0002
batch_size: 2
fast_test: False
lambda_L1: 100
lambda_LGAN: 1.0
name: normal
max_dataset_size: -1
gpu_ids: [0]
checkpoints_dir: './checkpoints'
epoch: 'latest'
continue_train: False
load_iter: 0
display_freq: 50
print_freq: 50
save_latest_freq: 1000
verbose: False
suffix : ''
val_split_ratio: 0.2
seed: 10
n_workers: 2


# model params
model: 'pix2pix'
input_nc: 6
output_nc: 1
ngf : 64
ndf: 64
netD: 'basic'
netG: 'unet_256'
n_layers_D: 3
norm: 'batch'
init_type: 'normal'
init_gain: 0.02
no_dropout: False
gan_mode: 'vanilla'
pool_size: 0
lr_policy: 'linear'
lr_decay_iters: 50
beta1: 0.5


# dataset params
dataset:
  dataset_A:
    data_dir: '/media/oem/Local Disk/Phd-datasets/selected_semantickitti_with_rgb_projected'
    sensor:
      name: "HDL64"
      type: "spherical" # projective
      have_rgb: True
      fov_up: 3
      fov_down: -25 
      foh_left: 45
      foh_right: -45
      img_prop:
        width: 256
        height: 64
      img_means: #x,y,z, range, signal
        - 11.06
        - 0.25
        - -1.20
        - 12.29
        - 0.27
      img_stds: #x,y,z,range, signal
        - 10.10
        - 6.02
        - 0.78
        - 10.57
        - 0.13
      img_min:
        - 1.26
        - -56.34
        - -31.95
        - 1.78
        - 0.0
      img_max:
        - 79.99
        - 56.48
        - 2.95
        - 80.22
        - 0.99